-- MySQL Script generated by MySQL Workbench
-- jue 22 feb 2018 09:35:45 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bbddsitters
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bbddsitters
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bbddsitters` DEFAULT CHARACTER SET utf8 ;
USE `bbddsitters` ;

-- -----------------------------------------------------
-- Table `bbddsitters`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bbddsitters`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NULL,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `provincia` VARCHAR(45) NULL,
  `tarifa` INT NULL,
  `descripcion` VARCHAR(500) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `Login_UNIQUE` (`login` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bbddsitters`.`perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bbddsitters`.`perfil` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `Nombre_UNIQUE` (`nombre` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bbddsitters`.`comentario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bbddsitters`.`comentario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `origen` INT NULL,
  `destino` INT NULL,
  `puntuacion` INT NULL,
  `comentario` VARCHAR(500) NULL,
  `fecha` DATE NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Comentarios_Usuario_Origen_idx` (`origen` ASC),
  INDEX `fk_Comentarios_Usuario_Destino_idx` (`destino` ASC),
  CONSTRAINT `fk_comentarios_origen`
    FOREIGN KEY (`origen`)
    REFERENCES `bbddsitters`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comentarios_destino`
    FOREIGN KEY (`destino`)
    REFERENCES `bbddsitters`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bbddsitters`.`anuncio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bbddsitters`.`anuncio` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuario` INT NULL,
  `asunto` VARCHAR(100) NULL,
  `cuerpo` VARCHAR(500) NULL,
  `fecha` DATE NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Anuncios_Usuario_idx` (`usuario` ASC),
  CONSTRAINT `fk_Anuncios_Usuario`
    FOREIGN KEY (`usuario`)
    REFERENCES `bbddsitters`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bbddsitters`.`mensaje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bbddsitters`.`mensaje` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `origen` INT NULL,
  `destino` INT NULL,
  `asunto` VARCHAR(100) NULL,
  `cuerpo` VARCHAR(500) NULL,
  `fecha` DATE NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Mensajes_Usuario_Origen_idx` (`origen` ASC),
  INDEX `fk_Mensajes_Usuario_Destino_idx` (`destino` ASC),
  CONSTRAINT `fk_Mensajes_Usuario_Origen`
    FOREIGN KEY (`origen`)
    REFERENCES `bbddsitters`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Mensajes_Usuario_Destino`
    FOREIGN KEY (`destino`)
    REFERENCES `bbddsitters`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE USER 'admin' IDENTIFIED BY 'admin1234';

GRANT ALL ON `bbddsitters`.* TO 'admin';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
