-- MySQL Script generated by MySQL Workbench
-- sáb 10 feb 2018 20:00:03 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuarios` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Login` VARCHAR(45) NULL,
  `Nombre` VARCHAR(45) NULL,
  `Password` VARCHAR(45) NULL,
  `Email` VARCHAR(45) NULL,
  `Provincia` VARCHAR(45) NULL,
  `Tarifa` INT NULL,
  `Descripcion` VARCHAR(500) NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `Login_UNIQUE` (`Login` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Perfiles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Perfiles` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `Nombre_UNIQUE` (`Nombre` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Comentarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Comentarios` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Id_Usuario_Origen` INT NULL,
  `Id_Usuario_Destino` INT NULL,
  `Puntuacion` INT NULL,
  `Comentario` VARCHAR(500) NULL,
  `Fecha` DATE NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_Comentarios_Usuario_Origen_idx` (`Id_Usuario_Origen` ASC),
  INDEX `fk_Comentarios_Usuario_Destino_idx` (`Id_Usuario_Destino` ASC),
  CONSTRAINT `fk_Comentarios_Usuario_Origen`
    FOREIGN KEY (`Id_Usuario_Origen`)
    REFERENCES `mydb`.`Usuarios` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Comentarios_Usuario_Destino`
    FOREIGN KEY (`Id_Usuario_Destino`)
    REFERENCES `mydb`.`Usuarios` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Anuncios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Anuncios` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Id_Usuario` INT NULL,
  `Asunto` VARCHAR(100) NULL,
  `Cuerpo` VARCHAR(500) NULL,
  `Fecha` DATE NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_Anuncios_Usuario_idx` (`Id_Usuario` ASC),
  CONSTRAINT `fk_Anuncios_Usuario`
    FOREIGN KEY (`Id_Usuario`)
    REFERENCES `mydb`.`Usuarios` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Mensajes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Mensajes` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Id_Usuario_Origen` INT NULL,
  `Id_Usuario_Destino` INT NULL,
  `Asunto` VARCHAR(100) NULL,
  `Cuerpo` VARCHAR(500) NULL,
  `Fecha` VARCHAR(45) NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_Mensajes_Usuario_Origen_idx` (`Id_Usuario_Origen` ASC),
  INDEX `fk_Mensajes_Usuario_Destino_idx` (`Id_Usuario_Destino` ASC),
  CONSTRAINT `fk_Mensajes_Usuario_Origen`
    FOREIGN KEY (`Id_Usuario_Origen`)
    REFERENCES `mydb`.`Usuarios` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Mensajes_Usuario_Destino`
    FOREIGN KEY (`Id_Usuario_Destino`)
    REFERENCES `mydb`.`Usuarios` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Rel_Usuarios_Perfiles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Rel_Usuarios_Perfiles` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Id_Usuario` INT NULL,
  `Id_Perfil` INT NULL,
  `Fecha` DATE NULL,
  `Activo` INT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_Rel_Usuarios_Perfiles_U_idx` (`Id_Usuario` ASC),
  INDEX `fk_Rel_Usuarios_Perfiles_P_idx` (`Id_Perfil` ASC),
  CONSTRAINT `fk_Rel_Usuarios_Perfiles_U`
    FOREIGN KEY (`Id_Usuario`)
    REFERENCES `mydb`.`Usuarios` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Rel_Usuarios_Perfiles_P`
    FOREIGN KEY (`Id_Perfil`)
    REFERENCES `mydb`.`Perfiles` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Rel_Usuarios_Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Rel_Usuarios_Usuarios` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Id_Usuario_Sitter` INT NULL,
  `Id_Usuario_Centro` INT NULL,
  `Fecha` DATE NULL,
  `Activo` INT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_Rel_Usuarios_Usuarios_U_idx` (`Id_Usuario_Sitter` ASC),
  INDEX `fk_Rel_Usuarios_Usuarios_C_idx` (`Id_Usuario_Centro` ASC),
  CONSTRAINT `fk_Rel_Usuarios_Usuarios_S`
    FOREIGN KEY (`Id_Usuario_Sitter`)
    REFERENCES `mydb`.`Usuarios` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Rel_Usuarios_Usuarios_C`
    FOREIGN KEY (`Id_Usuario_Centro`)
    REFERENCES `mydb`.`Usuarios` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Relación entre un usuario (Star Sitter) y un Centro';

CREATE USER 'Admin' IDENTIFIED BY 'admin1234';

GRANT ALL ON `mydb`.* TO 'Admin';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
